# Generated by nixwin - do not edit (regenerate with `nixwin install`).
#
# Windows cross-compilation toolchain for CMake (clang-cl + lld-link).
#
# Usage:
#   export CMAKE_TOOLCHAIN_FILE=$NIXWIN_SYSROOT/toolchain.cmake
#   export CMAKE_CLANG_VFS_OVERLAY=$NIXWIN_SYSROOT/vfsoverlay.json
#   cmake -B build [-DTARGET_PLATFORM Win32]
#
# The sysroot is resolved from (in order): the NIXWIN_SYSROOT CMake variable,
# the NIXWIN_SYSROOT environment variable, or the directory of this file.

if(NOT DEFINED NIXWIN_SYSROOT OR "${NIXWIN_SYSROOT}" STREQUAL "")
  if(DEFINED ENV{NIXWIN_SYSROOT} AND NOT "$ENV{NIXWIN_SYSROOT}" STREQUAL "")
    set(NIXWIN_SYSROOT "$ENV{NIXWIN_SYSROOT}")
  else()
    set(NIXWIN_SYSROOT "${CMAKE_CURRENT_LIST_DIR}")
  endif()
endif()

set(NIXWIN_CRT_VERSION "{{crt_version}}")
set(NIXWIN_SDK_VERSION "{{sdk_version}}")
set(NIXWIN_VFS_OVERLAY "${NIXWIN_SYSROOT}/vfsoverlay.json")
set(CMAKE_CLANG_VFS_OVERLAY "${NIXWIN_VFS_OVERLAY}")

set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_AR llvm-lib)
set(CMAKE_LINKER lld-link)

# Target architecture: defaults to the primary architecture of this sysroot,
# overridable with -DTARGET_PLATFORM=Win32 (x86) or Win64 (x86_64).
set(NIXWIN_TARGET_ARCH "{{default_arch}}")
if(DEFINED TARGET_PLATFORM)
  if(TARGET_PLATFORM STREQUAL "Win32")
    set(NIXWIN_TARGET_ARCH "x86")
  elseif(TARGET_PLATFORM STREQUAL "Win64")
    set(NIXWIN_TARGET_ARCH "x86_64")
  endif()
endif()

if(NIXWIN_TARGET_ARCH STREQUAL "x86")
  set(_nixwin_ms_arch "x86")
  set(_nixwin_triple "i686-pc-windows-msvc")
  set(CMAKE_SYSTEM_PROCESSOR "x86")
elseif(NIXWIN_TARGET_ARCH STREQUAL "x86_64")
  set(_nixwin_ms_arch "x64")
  set(_nixwin_triple "x86_64-pc-windows-msvc")
  set(CMAKE_SYSTEM_PROCESSOR "x86_64")
elseif(NIXWIN_TARGET_ARCH STREQUAL "aarch64")
  set(_nixwin_ms_arch "arm64")
  set(_nixwin_triple "aarch64-pc-windows-msvc")
  set(CMAKE_SYSTEM_PROCESSOR "aarch64")
else()
  set(_nixwin_ms_arch "arm")
  set(_nixwin_triple "armv7-pc-windows-msvc")
  set(CMAKE_SYSTEM_PROCESSOR "arm")
endif()

set(_nixwin_cflags
  "--target=${_nixwin_triple}"
  "/winsysroot \"${NIXWIN_SYSROOT}\""
  "-Xclang -ivfsoverlay -Xclang \"${NIXWIN_VFS_OVERLAY}\"")
string(JOIN " " _nixwin_cflags ${_nixwin_cflags})

set(CMAKE_C_FLAGS_INIT "${_nixwin_cflags}")
set(CMAKE_CXX_FLAGS_INIT "${_nixwin_cflags}")

set(CMAKE_EXE_LINKER_FLAGS_INIT "/vfsoverlay:\"${NIXWIN_VFS_OVERLAY}\"")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")

set(CMAKE_FIND_ROOT_PATH "${NIXWIN_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)