# Generated by nixwin (`nixwin setup --cmake`) - do not edit.
#
# Auto-selects the sysroot toolchain matching a project-local `.nixwin.json`,
# falling back to the default sysroot. Use with:
#   export CMAKE_TOOLCHAIN_FILE=<this file>

if(NOT DEFINED NIXWIN_DATA OR "${NIXWIN_DATA}" STREQUAL "")
  if(DEFINED ENV{NIXWIN_DATA} AND NOT "$ENV{NIXWIN_DATA}" STREQUAL "")
    set(NIXWIN_DATA "$ENV{NIXWIN_DATA}")
  else()
    set(NIXWIN_DATA "$ENV{HOME}/.local/share/nixwin")
  endif()
endif()

set(_nixwin_sysroot "")
foreach(_nw_dir "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_LIST_DIR}")
  if(EXISTS "${_nw_dir}/.nixwin.json")
    file(READ "${_nw_dir}/.nixwin.json" _nw_lock)
    if(_nw_lock MATCHES "\"tag\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]+)\"")
      set(_nixwin_sysroot "${NIXWIN_DATA}/sysroots/${CMAKE_MATCH_1}")
    endif()
    break()
  endif()
endforeach()

if("${_nixwin_sysroot}" STREQUAL "")
  if(DEFINED ENV{NIXWIN_SYSROOT} AND NOT "$ENV{NIXWIN_SYSROOT}" STREQUAL "")
    set(_nixwin_sysroot "$ENV{NIXWIN_SYSROOT}")
  else()
    get_filename_component(_nixwin_sysroot "${NIXWIN_DATA}/sysroot" REALPATH)
  endif()
endif()

include("${_nixwin_sysroot}/toolchain.cmake")