use anyhow::{Context as _, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// A parsed clang VFS overlay document (`vfsoverlay.json`).
///
/// Matches the format produced by xwin: kebab-case keys with stringified
/// booleans.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OverlayDoc {
    #[serde(default)]
    pub version: u32,
    #[serde(rename = "case-sensitive", with = "string_bool", default)]
    pub case_sensitive: bool,
    #[serde(
        rename = "overlay-relative",
        with = "string_bool",
        default = "default_true"
    )]
    pub overlay_relative: bool,
    #[serde(rename = "root-relative", default = "default_root_relative")]
    pub root_relative: String,
    #[serde(default)]
    pub roots: Vec<Entry>,
}

impl Default for OverlayDoc {
    fn default() -> Self {
        Self {
            version: 0,
            case_sensitive: false,
            overlay_relative: true,
            root_relative: "overlay-dir".to_owned(),
            roots: Vec::new(),
        }
    }
}

fn default_true() -> bool {
    true
}

fn default_root_relative() -> String {
    "overlay-dir".to_owned()
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
#[serde(tag = "type")]
pub enum Entry {
    File {
        name: String,
        #[serde(rename = "external-contents")]
        external_contents: String,
    },
    DirectoryRemap {
        name: String,
        #[serde(rename = "external-contents")]
        external_contents: String,
    },
}

mod string_bool {
    use serde::{Deserializer, Serializer, de};

    pub fn serialize<S: Serializer>(value: &bool, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&value.to_string().to_lowercase())
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<bool, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct V;

        impl de::Visitor<'_> for V {
            type Value = bool;

            fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str("a boolean or a stringified boolean")
            }

            fn visit_bool<E: de::Error>(self, v: bool) -> Result<bool, E> {
                Ok(v)
            }

            fn visit_str<E: de::Error>(self, v: &str) -> Result<bool, E> {
                v.parse()
                    .map_err(|_| de::Error::invalid_value(de::Unexpected::Str(v), &self))
            }
        }

        deserializer.deserialize_any(V)
    }
}

/// Loads an overlay document, returning `None` if the file doesn't exist
pub fn load(path: &Path) -> Result<Option<OverlayDoc>> {
    if !path.exists() {
        return Ok(None);
    }
    let contents =
        std::fs::read(path).with_context(|| format!("unable to read {}", path.display()))?;
    serde_json::from_slice(&contents)
        .map(Some)
        .with_context(|| format!("unable to parse {}", path.display()))
}

/// Merges the existing sysroot overlay (previous installs) with the overlay
/// generated by the latest splat run, deduplicating entries by `name`
/// (existing entries win).
pub fn merge(old: Option<OverlayDoc>, new: Option<OverlayDoc>) -> Option<OverlayDoc> {
    match (old, new) {
        (None, None) => None,
        (old, None) => old,
        (old, Some(new)) => {
            let mut doc = new;
            if let Some(old) = old {
                let names: std::collections::HashSet<String> =
                    doc.roots.iter().map(|e| e.name().to_owned()).collect();
                doc.roots.extend(
                    old.roots
                        .into_iter()
                        .filter(|e| !names.contains(e.name())),
                );
            }
            Some(doc)
        }
    }
}

impl Entry {
    pub fn name(&self) -> &str {
        match self {
            Entry::File { name, .. } | Entry::DirectoryRemap { name, .. } => name,
        }
    }
}

/// Writes an overlay document (or an empty one, so consumers can always
/// reference the file)
pub fn write(path: &Path, doc: Option<&OverlayDoc>) -> Result<()> {
    let doc = doc.cloned().unwrap_or_default();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("unable to create {}", parent.display()))?;
    }
    let file = std::fs::File::create(path)
        .with_context(|| format!("unable to create {}", path.display()))?;
    serde_json::to_writer_pretty(
        std::io::BufWriter::new(file),
        &doc,
    )
    .with_context(|| format!("unable to write {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file_entry(name: &str, ext: &str) -> Entry {
        Entry::File {
            name: name.to_owned(),
            external_contents: ext.to_owned(),
        }
    }

    #[test]
    fn merge_dedupes_by_name() {
        let old = OverlayDoc {
            roots: vec![file_entry("a", "a-real"), file_entry("b", "b-real")],
            ..OverlayDoc::default()
        };
        let new = OverlayDoc {
            roots: vec![file_entry("b", "b-new"), file_entry("c", "c-new")],
            ..OverlayDoc::default()
        };

        let merged = merge(Some(old), Some(new)).unwrap();
        let names: Vec<&str> = merged.roots.iter().map(|e| e.name()).collect();
        assert_eq!(names, vec!["b", "c", "a"]);
        // entries from the latest run win on conflicts
        assert_eq!(
            merged.roots.iter().find(|e| e.name() == "b").unwrap(),
            &file_entry("b", "b-new")
        );
    }

    #[test]
    fn merge_missing_sides() {
        let new = OverlayDoc {
            roots: vec![file_entry("a", "a")],
            ..OverlayDoc::default()
        };
        assert_eq!(merge(None, Some(new.clone())).unwrap().roots, new.roots);
        assert_eq!(merge(Some(new.clone()), None).unwrap().roots, new.roots);
        assert!(merge(None, None).is_none());
    }

    #[test]
    fn xwin_format_roundtrip() {
        let json = r#"{
  "version": 0,
  "case-sensitive": "false",
  "overlay-relative": "true",
  "root-relative": "overlay-dir",
  "roots": [
    {
      "type": "file",
      "name": "Windows Kits/10/Include/10.0.26100/shared/BaseTsd.h",
      "external-contents": "Windows Kits/10/Include/10.0.26100/shared/basetsd.h"
    },
    {
      "type": "directory-remap",
      "name": "a/b",
      "external-contents": "c/d"
    }
  ]
}"#;
        let doc: OverlayDoc = serde_json::from_str(json).unwrap();
        assert!(!doc.case_sensitive);
        assert!(doc.overlay_relative);
        assert_eq!(doc.roots.len(), 2);
        assert!(matches!(doc.roots[1], Entry::DirectoryRemap { .. }));

        let round: OverlayDoc = serde_json::from_str(
            &serde_json::to_string_pretty(&doc).unwrap(),
        )
        .unwrap();
        assert!(!round.case_sensitive);
    }

    #[test]
    fn write_creates_empty_doc() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("vfsoverlay.json");
        write(&path, None).unwrap();
        let loaded = load(&path).unwrap().unwrap();
        assert_eq!(loaded.roots, Vec::<Entry>::new());
        assert_eq!(loaded.root_relative, "overlay-dir");
    }
}
